[package]
name = "egui-multiwin"
version = "0.1.1"
description="A crate that allows for multiple windows with egui"
license = "MIT OR Apache-2.0"
edition = "2018"
publish = ["crates-io"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.19.0"
egui_glow = { version = "0.19.0", features = ["clipboard", "winit", "links"]}
glow = "0.11"
glutin = "0.29.1"
thiserror = "1.0"
